# Use a high warning level to help preventing some classes of bugs.
function(pipsqueak_set_warnings target)
  if (MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(FAIL_ON_WARNINGS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(FAIL_ON_WARNINGS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
